import {
  boolean,
  integer,
  jsonb,
  numeric,
  pgTable,
  text,
  timestamp,
  varchar,
  date,
} from 'drizzle-orm/pg-core';

export const organizations = pgTable('organizations', {
  id: varchar('id').primaryKey(),
  name: varchar('name').notNull(),
  slug: varchar('slug').notNull(),
  isDemo: boolean('is_demo').notNull().default(false),
  demoExpiresAt: timestamp('demo_expires_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const users = pgTable('users', {
  id: varchar('id').primaryKey(),
  organizationId: varchar('organization_id').notNull(),
  email: varchar('email').notNull(),
  name: varchar('name').notNull(),
  role: varchar('role').notNull().default('member'),
  uid: varchar('uid'),
  passwordHash: text('password_hash'),
  phone: varchar('phone'),
  companyName: varchar('company_name'),
  portfolioSize: varchar('portfolio_size'),
  primaryMarket: varchar('primary_market'),
  currentAddress: varchar('current_address'),
  monthlyIncome: varchar('monthly_income'),
  employmentStatus: varchar('employment_status'),
  moveInDate: varchar('move_in_date'),
  occupantsCount: integer('occupants_count'),
  hasPets: varchar('has_pets'),
  tradeSpecialty: varchar('trade_specialty'),
  hourlyRate: varchar('hourly_rate'),
  propertyTypes: varchar('property_types'),
  managementFee: varchar('management_fee'),
  serviceRadius: varchar('service_radius'),
  emergencyDispatch: varchar('emergency_dispatch'),
  authProvider: varchar('auth_provider'),
  authProviderSubject: varchar('auth_provider_subject'),
  avatarUrl: varchar('avatar_url'),
  disabledAt: timestamp('disabled_at', { withTimezone: true }),
  lastLoginAt: timestamp('last_login_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const authSessions = pgTable('auth_sessions', {
  id: varchar('id').primaryKey(),
  userId: varchar('user_id').notNull(),
  tokenHash: varchar('token_hash').notNull(),
  expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  lastSeenAt: timestamp('last_seen_at', { withTimezone: true }).notNull().defaultNow(),
});

export const properties = pgTable('properties', {
  id: varchar('id').primaryKey(),
  organizationId: varchar('organization_id').notNull(),
  ownerId: varchar('owner_id'),
  address: varchar('address').notNull(),
  city: varchar('city').notNull(),
  state: varchar('state').notNull(),
  zip: varchar('zip').notNull(),
  county: varchar('county').notNull(),
  apn: varchar('apn').notNull(),
  propertyType: varchar('property_type').notNull(),
  unitsCount: integer('units_count').notNull().default(1),
  squareFeet: integer('square_feet').notNull().default(0),
  yearBuilt: integer('year_built'),
  estimatedValue: numeric('estimated_value').notNull().default('0'),
  assessedTaxValue: numeric('assessed_tax_value').notNull().default('0'),
  estimatedEquity: numeric('estimated_equity').notNull().default('0'),
  mortgageBalance: numeric('mortgage_balance').notNull().default('0'),
  isAbsenteeOwner: boolean('is_absentee_owner').notNull().default(false),
  isCorporateOwned: boolean('is_corporate_owned').notNull().default(false),
  taxDelinquent: boolean('tax_delinquent').notNull().default(false),
  lastSaleDate: date('last_sale_date'),
  lastSalePrice: numeric('last_sale_price'),
  provenance: jsonb('provenance').notNull().default({}),
  bedrooms: numeric('bedrooms'),
  bathrooms: numeric('bathrooms'),
  lotSizeSqft: integer('lot_size_sqft'),
  latitude: numeric('latitude'),
  longitude: numeric('longitude'),
  notes: text('notes'),
  tags: jsonb('tags').notNull().default([]),
  archivedAt: timestamp('archived_at', { withTimezone: true }),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const propertyOwners = pgTable('property_owners', {
  id: varchar('id').primaryKey(),
  organizationId: varchar('organization_id').notNull(),
  name: varchar('name').notNull(),
  entityType: varchar('entity_type').notNull().default('individual'),
  mailingAddress: varchar('mailing_address'),
  mailingCity: varchar('mailing_city'),
  mailingState: varchar('mailing_state'),
  mailingZip: varchar('mailing_zip'),
  phoneNumbers: jsonb('phone_numbers').notNull().default([]),
  emailAddresses: jsonb('email_addresses').notNull().default([]),
  propertiesOwnedCount: integer('properties_owned_count').notNull().default(1),
  totalPortfolioValue: numeric('total_portfolio_value').notNull().default('0'),
  totalPortfolioEquity: numeric('total_portfolio_equity').notNull().default('0'),
  notes: text('notes'),
  tags: jsonb('tags').notNull().default([]),
  archivedAt: timestamp('archived_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

export const leads = pgTable('leads', {
  id: varchar('id').primaryKey(),
  organizationId: varchar('organization_id').notNull(),
  ownerId: varchar('owner_id'),
  primaryPropertyId: varchar('primary_property_id'),
  leadScore: integer('lead_score').notNull().default(0),
  classification: varchar('classification').notNull().default('nurture'),
  factors: jsonb('factors').notNull().default([]),
  stage: varchar('stage').notNull().default('identified'),
  assignedAgent: varchar('assigned_agent').notNull().default('sub_agent_2'),
  dncCompliant: boolean('dnc_compliant').notNull().default(true),
  lastActivityDate: timestamp('last_activity_date', { withTimezone: true }).notNull().defaultNow(),
  nextRecommendedAction: text('next_recommended_action'),
  title: varchar('title'),
  source: varchar('source'),
  contactId: varchar('contact_id'),
  propertyOwnerId: varchar('property_owner_id'),
  assignedUserId: varchar('assigned_user_id'),
  tags: jsonb('tags').notNull().default([]),
  value: numeric('value').notNull().default('0'),
  archivedAt: timestamp('archived_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

const ts = (name: string) => timestamp(name, { withTimezone: true });
const created = () => ts('created_at').notNull().defaultNow();

export const contacts = pgTable('contacts', {
  id: varchar('id').primaryKey(),
  organizationId: varchar('organization_id').notNull(),
  firstName: varchar('first_name').notNull(),
  lastName: varchar('last_name').notNull().default(''),
  email: varchar('email'),
  phone: varchar('phone'),
  company: varchar('company'),
  contactType: varchar('contact_type').notNull().default('prospect'),
  propertyOwnerId: varchar('property_owner_id'),
  assignedUserId: varchar('assigned_user_id'),
  source: varchar('source'),
  tags: jsonb('tags').notNull().default([]),
  doNotCall: boolean('do_not_call').notNull().default(false),
  lastContactedAt: ts('last_contacted_at'),
  archivedAt: ts('archived_at'),
  createdAt: created(),
  updatedAt: ts('updated_at').notNull().defaultNow(),
});

export const tasks = pgTable('tasks', {
  id: varchar('id').primaryKey(),
  organizationId: varchar('organization_id').notNull(),
  title: varchar('title').notNull(),
  description: text('description'),
  dueAt: ts('due_at'),
  status: varchar('status').notNull().default('open'),
  priority: varchar('priority').notNull().default('normal'),
  assignedUserId: varchar('assigned_user_id'),
  createdBy: varchar('created_by'),
  contactId: varchar('contact_id'),
  leadId: varchar('lead_id'),
  propertyId: varchar('property_id'),
  campaignId: varchar('campaign_id'),
  callId: varchar('call_id'),
  completedAt: ts('completed_at'),
  createdAt: created(),
  updatedAt: ts('updated_at').notNull().defaultNow(),
});

export const notes = pgTable('notes', {
  id: varchar('id').primaryKey(),
  organizationId: varchar('organization_id').notNull(),
  body: text('body').notNull(),
  authorId: varchar('author_id'),
  contactId: varchar('contact_id'),
  leadId: varchar('lead_id'),
  propertyId: varchar('property_id'),
  propertyOwnerId: varchar('property_owner_id'),
  campaignId: varchar('campaign_id'),
  callId: varchar('call_id'),
  createdAt: created(),
});

export const activities = pgTable('activities', {
  id: varchar('id').primaryKey(),
  organizationId: varchar('organization_id').notNull(),
  type: varchar('type').notNull(),
  summary: text('summary').notNull(),
  actorKind: varchar('actor_kind').notNull().default('user'),
  actorUserId: varchar('actor_user_id'),
  contactId: varchar('contact_id'),
  leadId: varchar('lead_id'),
  propertyId: varchar('property_id'),
  propertyOwnerId: varchar('property_owner_id'),
  campaignId: varchar('campaign_id'),
  callId: varchar('call_id'),
  taskId: varchar('task_id'),
  workflowRunId: varchar('workflow_run_id'),
  metadata: jsonb('metadata').notNull().default({}),
  createdAt: created(),
});

export const campaigns = pgTable('campaigns', {
  id: varchar('id').primaryKey(),
  organizationId: varchar('organization_id').notNull(),
  name: varchar('name').notNull(),
  description: text('description'),
  script: text('script'),
  status: varchar('status').notNull().default('draft'),
  createdBy: varchar('created_by'),
  startedAt: ts('started_at'),
  completedAt: ts('completed_at'),
  archivedAt: ts('archived_at'),
  createdAt: created(),
  updatedAt: ts('updated_at').notNull().defaultNow(),
});

export const campaignContacts = pgTable('campaign_contacts', {
  id: varchar('id').primaryKey(),
  organizationId: varchar('organization_id').notNull(),
  campaignId: varchar('campaign_id').notNull(),
  contactId: varchar('contact_id').notNull(),
  leadId: varchar('lead_id'),
  status: varchar('status').notNull().default('pending'),
  attempts: integer('attempts').notNull().default(0),
  lastOutcome: varchar('last_outcome'),
  lastCalledAt: ts('last_called_at'),
  createdAt: created(),
});

export const calls = pgTable('calls', {
  id: varchar('id').primaryKey(),
  organizationId: varchar('organization_id').notNull(),
  contactId: varchar('contact_id'),
  leadId: varchar('lead_id'),
  propertyId: varchar('property_id'),
  campaignId: varchar('campaign_id'),
  userId: varchar('user_id'),
  direction: varchar('direction').notNull().default('outbound'),
  toNumber: varchar('to_number').notNull(),
  status: varchar('status').notNull().default('dialing'),
  outcome: varchar('outcome'),
  provider: varchar('provider').notNull().default('simulated'),
  isSimulated: boolean('is_simulated').notNull().default(true),
  providerCallId: varchar('provider_call_id'),
  failureReason: text('failure_reason'),
  notes: text('notes'),
  startedAt: ts('started_at').notNull().defaultNow(),
  answeredAt: ts('answered_at'),
  endedAt: ts('ended_at'),
  durationSeconds: integer('duration_seconds'),
  createdAt: created(),
  updatedAt: ts('updated_at').notNull().defaultNow(),
});

export const workflows = pgTable('workflows', {
  id: varchar('id').primaryKey(),
  organizationId: varchar('organization_id').notNull(),
  name: varchar('name').notNull(),
  description: text('description'),
  triggerType: varchar('trigger_type').notNull(),
  conditions: jsonb('conditions').notNull().default([]),
  actions: jsonb('actions').notNull().default([]),
  enabled: boolean('enabled').notNull().default(true),
  createdBy: varchar('created_by'),
  lastRunAt: ts('last_run_at'),
  createdAt: created(),
  updatedAt: ts('updated_at').notNull().defaultNow(),
});

export const workflowRuns = pgTable('workflow_runs', {
  id: varchar('id').primaryKey(),
  organizationId: varchar('organization_id').notNull(),
  workflowId: varchar('workflow_id').notNull(),
  status: varchar('status').notNull().default('queued'),
  triggerType: varchar('trigger_type').notNull(),
  triggerPayload: jsonb('trigger_payload').notNull().default({}),
  conditionsMet: boolean('conditions_met'),
  steps: jsonb('steps').notNull().default([]),
  error: text('error'),
  startedAt: ts('started_at'),
  finishedAt: ts('finished_at'),
  createdAt: created(),
});

export const agentRuns = pgTable('agent_runs', {
  id: varchar('id').primaryKey(),
  organizationId: varchar('organization_id').notNull(),
  agentKey: varchar('agent_key').notNull(),
  status: varchar('status').notNull().default('queued'),
  triggeredBy: varchar('triggered_by'),
  input: jsonb('input').notNull().default({}),
  output: jsonb('output'),
  error: text('error'),
  startedAt: ts('started_at'),
  finishedAt: ts('finished_at'),
  createdAt: created(),
});
